# PLACEHOLDERS
# <prefix> -> For Bot Prefix

# Language Supports
# https://github.com/Fenish/modulecord-modules/blob/main/locales/

Token:
Locale: English

# Types: PLAYING, LISTENING
# Statuses: ONLINE, OFFLINE, DND, IDLE
Presence:
  Type: LISTENING
  Text: <prefix>Help
  Status: IDLE
